induction c with d hd generalizing b,
rw mul_zero a,
intro p,
rw mul_eq_zero_iff at p,
cases p with q r,
exfalso,
exact ha(q),
apply r,
intro P,
cases b,
rw mul_zero at P,
symmetry at P,
rw mul_eq_zero_iff at P,
cases P,
exfalso,
exact ha P,
symmetry at P,
exact P,
repeat {rw mul_succ at P},
apply succ_eq_succ_of_eq,
repeat {rw add_right_cancel_iff at P},
apply hd at P,
exact P,
