cases hab with P Q,
cases hba with R S,
rw S at Q,
symmetry at Q,
rw add_assoc b R P at Q,
have T := eq_zero_of_add_right_eq_self Q,
have U := add_right_eq_zero T,
rw U at S,
rw add_zero b at S,
exact S,
